### ISSUE TITLE
TypeError: create() got an unexpected keyword argument 'prepend_key'

### ISSUE THREAD

**Issue by flyPpig** [huaweicloudsdk/sdk-python#6]
调用 conn.orchestration.create_stack(**data) 创建stack时出现如下错误：

Traceback (most recent call last):
  File "stack.py", line 80, in <module>
    stack_create(conn)
  File "stack.py", line 31, in stack_create
    stack = conn.orchestration.create_stack(**data)
  File "/usr/lib/python2.7/site-packages/openstack/orchestration/v1/_proxy.py", line 43, in create_stack
    return self._create(res_type, **attrs)
  File "/usr/lib/python2.7/site-packages/openstack/proxy2.py", line 200, in _create
    return res.create(self._session, prepend_key=prepend_key)
TypeError: create() got an unexpected keyword argument 'prepend_key'

使用原生openstacksdk创建stack时正常，可以创建成功。

**Comment by flyPpig** [comment]
代码如下
[sdk_demo.zip](https://github.com/huaweicloudsdk/sdk-python/files/2430258/sdk_demo.zip)

除了创建stack，其他都可用
