### ISSUE TITLE
When will the SDK support python 3?

### ISSUE THREAD

**Issue by dan-bar-dov** [huaweicloudsdk/sdk-python#7]
What is the plan to move the SDK forward to python 3.6/3.7?

**Comment by IamFive** [comment]
I think it should support PY36 by default, what is the issue?

**Comment by dan-bar-dov** [comment]
I get the following error:
eddy@eddy-om-linux2:~/hec/test$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from openstack import connection
  File "/usr/local/lib/python3.6/dist-packages/openstack/connection.py", line 88, in <module>
    from openstack import aksksession as aksession
  File "/usr/local/lib/python3.6/dist-packages/openstack/aksksession.py", line 21, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'


This link explains that the module was renamed in Python 3:
https://docs.python.org/2/library/urlparse.htmlhttps://docs.python.org/2/library/urlparse.html

This is obviously only the first error. It proves that the openstack package was never run in Python 3

**Comment by IamFive** [comment]
It seems the AKSK feature breaks python3 support. 
I am not the commitor now, may the project manager will fix it.
